### ISSUE TITLE
Suggestion: Update font-family

### ISSUE THREAD

**Issue by forsbergplustwo** [microapps/Shopify-Embedded-App-Frontend-Framework#107]
Great project! Now that Shopify have changed their Admin font to use San Fransisco, I'd suggest that the project use one of the following Google Fonts:

Roboto
Open Sans

They are close matches to San Fransisco, and available to everyone. Roboto seems a little closer than Open Sans.

Image with comparision: http://cl.ly/Zz1I

**Comment by alexandresaiz** [comment]
@forsbergplustwo Would you mind creating a PR for this ? Great suggestion!
