### ISSUE TITLE
Non-responsive

### ISSUE THREAD

**Issue by SylarRuby** [microapps/Shopify-Embedded-App-Frontend-Framework#110]
Nothing is responsive. Any reason?

**Comment by alexandresaiz** [comment]
95% of Shopify merchants log into their Shopify apps dashboard from desktops. BUT! Yes! It's not responsive nor SASS at all. Would you like to help?

**Comment by SylarRuby** [comment]
Wow! 95%? Ohhhh. I dont mind. I'll see what I can cook up. I'll close this and once I have something, I'll request a PR 😉

**Comment by alexandresaiz** [comment]
👍👍👍👏🏻👏🏻👏🏻
