### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by milep** [microapps/Shopify-Embedded-App-Frontend-Framework#113]
Didn't find any licensing information?

**Comment by alexandresaiz** [comment]
Feel free to use it!

**Comment by milep** [comment]
Ok, thanks, but I suggest you add license file like https://github.com/Shopify/shopify_app/blob/master/LICENSE

Otherwise you are not giving any permissions for use by many countries laws.

**Comment by alexandresaiz** [comment]
Add it and we'll merge it
