### ISSUE TITLE
New red colour for Destroy button

### ISSUE THREAD

**Issue by alexandresaiz** [microapps/Shopify-Embedded-App-Frontend-Framework#14]
Shopify has updated the red for destroy button. See sshot:
https://www.dropbox.com/s/15ih8czv62o0i7z/Captura%20de%20pantalla%202015-03-16%2011.12.48.png?dl=0

**Comment by rafaelxavi** [comment]
Not only the destroy, but the primary and default ones as well. This issue is solved http://seaff.microapps.com

**Comment by alexandresaiz** [comment]
:+1:
