### ISSUE TITLE
Change the Confirm Modal screenshot considering new Destroy red colour

### ISSUE THREAD

**Issue by alexandresaiz** [microapps/Shopify-Embedded-App-Frontend-Framework#17]

**Comment by alexandresaiz** [comment]
This is the new one with the modified texts.
https://www.dropbox.com/s/v5dey89c5hn00hn/Captura%20de%20pantalla%202015-04-20%2016.16.53.png?dl=0
![captura de pantalla 2015-04-20 16 16 53](https://cloud.githubusercontent.com/assets/239624/7231910/babf3348-e778-11e4-9f27-f880c20454e7.png)

**Comment by alexandresaiz** [comment]
@jcarratala can you please do this. It's 1 minute task.

**Comment by jcarratala** [comment]
I'm working on it right now
