### ISSUE TITLE
Fix tooltip visualization in docs

### ISSUE THREAD

**Issue by jcarratala** [microapps/Shopify-Embedded-App-Frontend-Framework#62]
The tooltip label is over the "Code" word and hiding it in his doc section:
https://www.dropbox.com/s/qxngezaxnitsiu5/Screen%20Shot%202015-10-28%20at%2009.57.09.png?dl=0

**Comment by alexandresaiz** [comment]
Can you please be more specific?

El 28/10/2015, a les 9:48, jcarratala <notifications@github.com> va escriure:

**Comment by jcarratala** [comment]
I have edited the first comment
