### ISSUE TITLE
Fix buttons effect

### ISSUE THREAD

**Issue by jcarratala** [microapps/Shopify-Embedded-App-Frontend-Framework#63]
Remove underline decoration in all buttons:
https://www.dropbox.com/s/me522th6be0xs8c/Screen%20Shot%202015-10-28%20at%2009.51.48.png?dl=0

**Comment by alexandresaiz** [comment]
This are links which lead to some view, but don't follow a specific action. Are you sure it has to be removed?

Examples within Shopify admin would be good to discuss about this.


El 28/10/2015, a les 9:55, jcarratala <notifications@github.com> va escriure:

**Comment by jcarratala** [comment]
The following link shows two default buttons in the Shopify admin:
https://www.dropbox.com/s/9hvilz0lx1xbpps/Screen%20Shot%202015-10-28%20at%2012.00.52.png?dl=0
The right one (:hover selected) applies a shadow effect, but do not underline the text.

Here is another example of the same problem:
https://www.dropbox.com/s/h4lqeg7i3lf06i2/Screen%20Shot%202015-10-28%20at%2013.07.02.png?dl=0

And here the Shopify one:
https://www.dropbox.com/s/rihfkvw1xq2tjvd/Screen%20Shot%202015-10-28%20at%2013.12.49.png?dl=0

**Comment by alexandresaiz** [comment]
@jcarratala is it already done?

**Comment by jcarratala** [comment]
Not yet, I will fix it today
