### ISSUE TITLE
Add Shopify icons

### ISSUE THREAD

**Issue by jcarratala** [microapps/Shopify-Embedded-App-Frontend-Framework#69]
Add all Shopify merchant admin icons to SEAFF

**Comment by alexandresaiz** [comment]
Some of the existing ones in the following view xxx.myshopify.com/admin are:

https://cdn.shopify.com/s/assets/admin/home/text-insights/popular-searches-d73f5df49b5a16cfd6151888cd4d5e95.png
https://cdn.shopify.com/s/assets/admin/home/text-insights/top-referrer-b4a76cc3cc62dce7bd6699e6c6908548.svg
https://cdn.shopify.com/s/assets/admin/home/onboarding-tasks/onboarding-buy-button-2a4933fd1e1f3f63edb2a2123fd5fd71.png
https://cdn.shopify.com/s/assets/admin/home/text-insights/mobile-visitors-c8c8826115203217441a11dcd457d796.png

**Comment by sheetalwagh** [comment]
Hi Alex,

How are you?

Could you please remove my email id from  notification list.  I m still
getting lot .

Good Day

Regards,
Sheetal

**Comment by alexandresaiz** [comment]
@sheetalwagh you and only you can do so... trick: https://www.dropbox.com/s/al5oq4a34znef3d/Captura%20de%20pantalla%202015-10-29%2018.42.41.png?dl=0

**Comment by alexandresaiz** [comment]
@jcarratala closing as some have been already added. It's not described in the docs. Creating new issue for this.
