### ISSUE TITLE
Improve code in index

### ISSUE THREAD

**Issue by jcarratala** [microapps/Shopify-Embedded-App-Frontend-Framework#72]
Remove all abbreviations in document in order to be more intuitive.
![screen shot 2015-10-30 at 11 28 51](https://cloud.githubusercontent.com/assets/14334459/10843479/99ddd08a-7ef9-11e5-9d4d-1bc964c49da5.png)
What is "jqd"? This is an example of non intuitive name

**Comment by alexandresaiz** [comment]
@jcarratala I agreed you could use jqd in this case. So this issue is not needed. I close it.
