### ISSUE TITLE
Improve url presentation

### ISSUE THREAD

**Issue by jcarratala** [microapps/Shopify-Embedded-App-Frontend-Framework#73]
Is necessary to make things the more human readable as possible. Try to use another ways to include  image urls as in this example:

![screen shot 2015-10-30 at 11 35 38](https://cloud.githubusercontent.com/assets/14334459/10843642/70d5b382-7efa-11e5-9987-68d54c7555d7.png)

**Comment by alexandresaiz** [comment]
@jcarratala closing as already decided to include when posible the svg's itself within the css.
