### ISSUE TITLE
Update checkbox style

### ISSUE THREAD

**Issue by jcarratala** [microapps/Shopify-Embedded-App-Frontend-Framework#75]
Update checkbox style and code in documentation
![screen shot 2015-11-05 at 11 51 02](https://cloud.githubusercontent.com/assets/14334459/10966407/ac9f6bac-83b3-11e5-95f5-df568d505173.png)

**Comment by alexandresaiz** [comment]
@jcarratala this seems to be added within examples views (orders, products), but hasn't been updated in the main seaff. Closing and creating a new issue.
