### ISSUE TITLE
Why do you not use sass to write css?

### ISSUE THREAD

**Issue by piya23300** [microapps/Shopify-Embedded-App-Frontend-Framework#93]
I am so sorry if my english is not good.

Most css framework (bootstrap, foundation etc.) use sass 
and if you is Rails developer. you often use sass.
Most app build from Rails app.
Sass is useful for developer. I think you should use sass.

I would like to know why you do not use sass?

if you write it with sass I will help you ^^ even if I am back-end developer and I know a little sass.

**Comment by alexandresaiz** [comment]
hey @piya23300 this is an open source project. You can convert anything to sass and do a PR, we will definitely accept any improvement here even if it's a small contribution! Closing this as it's not a real exact issue.
